-- V10__add_product_sku.sql
-- Generated by generate_product_migration.py on 2026-06-18 22:51:58 UTC
-- Adds sku column and backfills values for databases that already ran V9 without sku.

ALTER TABLE product ADD COLUMN IF NOT EXISTS sku VARCHAR(50);
CREATE UNIQUE INDEX IF NOT EXISTS ux_product_sku ON product (sku) WHERE sku IS NOT NULL;

UPDATE product SET sku = 'MB-001' WHERE slug = 'makeup-bag-blue-bear' AND sku IS DISTINCT FROM 'MB-001';
UPDATE product SET sku = 'MB-002' WHERE slug = 'makeup-bag-ribbon-charm' AND sku IS DISTINCT FROM 'MB-002';
UPDATE product SET sku = 'MB-003' WHERE slug = 'makeup-bag-pink-blossoms' AND sku IS DISTINCT FROM 'MB-003';
UPDATE product SET sku = 'MB-004' WHERE slug = 'makeup-bag-vintage-garden' AND sku IS DISTINCT FROM 'MB-004';
UPDATE product SET sku = 'MB-005' WHERE slug = 'makeup-bag-cinnamoroll' AND sku IS DISTINCT FROM 'MB-005';
UPDATE product SET sku = 'MB-006' WHERE slug = 'makeup-bag-fluffy-cat' AND sku IS DISTINCT FROM 'MB-006';
UPDATE product SET sku = 'MB-007' WHERE slug = 'makeup-bag-teddy-dot' AND sku IS DISTINCT FROM 'MB-007';
UPDATE product SET sku = 'MB-008' WHERE slug = 'makeup-bag-quilt-bloom' AND sku IS DISTINCT FROM 'MB-008';
UPDATE product SET sku = 'MB-009' WHERE slug = 'makeup-bag-soft-cloud' AND sku IS DISTINCT FROM 'MB-009';
UPDATE product SET sku = 'MB-010' WHERE slug = 'makeup-bag-golden-teddy' AND sku IS DISTINCT FROM 'MB-010';
UPDATE product SET sku = 'MB-011' WHERE slug = 'makeup-bag-pink-bows' AND sku IS DISTINCT FROM 'MB-011';
UPDATE product SET sku = 'MB-012' WHERE slug = 'makeup-bag-pastel-stripes' AND sku IS DISTINCT FROM 'MB-012';
UPDATE product SET sku = 'TC-001' WHERE slug = 'tissue-box-cover-blue-life-bread' AND sku IS DISTINCT FROM 'TC-001';
UPDATE product SET sku = 'TC-002' WHERE slug = 'tissue-box-cover-green-life-bread' AND sku IS DISTINCT FROM 'TC-002';
UPDATE product SET sku = 'TC-003' WHERE slug = 'tissue-box-cover-demae-iccho' AND sku IS DISTINCT FROM 'TC-003';
UPDATE product SET sku = 'TC-004' WHERE slug = 'tissue-box-cover-white-rabbit-candy' AND sku IS DISTINCT FROM 'TC-004';
UPDATE product SET sku = 'TC-005' WHERE slug = 'tissue-box-cover-aeroplane-chess' AND sku IS DISTINCT FROM 'TC-005';
UPDATE product SET sku = 'TC-006' WHERE slug = 'tissue-box-cover-mtr-station' AND sku IS DISTINCT FROM 'TC-006';
UPDATE product SET sku = 'TC-007' WHERE slug = 'tissue-box-cover-red-white-blue-bag-r' AND sku IS DISTINCT FROM 'TC-007';
UPDATE product SET sku = 'TC-008' WHERE slug = 'tissue-box-cover-red-white-blue-bag-b' AND sku IS DISTINCT FROM 'TC-008';
UPDATE product SET sku = 'TC-009' WHERE slug = 'tissue-box-cover-red-white-blue-bag-s' AND sku IS DISTINCT FROM 'TC-009';
UPDATE product SET sku = 'TC-010' WHERE slug = 'tissue-box-cover-cha-chaan-teng' AND sku IS DISTINCT FROM 'TC-010';
UPDATE product SET sku = 'TC-011' WHERE slug = 'tissue-box-cover-street-name-sign' AND sku IS DISTINCT FROM 'TC-011';
UPDATE product SET sku = 'TC-012' WHERE slug = 'tissue-box-cover-old-hong-kong' AND sku IS DISTINCT FROM 'TC-012';
UPDATE product SET sku = 'TC-013' WHERE slug = 'tissue-box-cover-canada' AND sku IS DISTINCT FROM 'TC-013';
UPDATE product SET sku = 'MP-001' WHERE slug = 'mini-pouch-blue-life-bread' AND sku IS DISTINCT FROM 'MP-001';
UPDATE product SET sku = 'MP-002' WHERE slug = 'mini-pouch-demae-iccho' AND sku IS DISTINCT FROM 'MP-002';
UPDATE product SET sku = 'MP-003' WHERE slug = 'mini-pouch-white-rabbit-candy' AND sku IS DISTINCT FROM 'MP-003';
UPDATE product SET sku = 'MP-004' WHERE slug = 'mini-pouch-aeroplane-chess' AND sku IS DISTINCT FROM 'MP-004';
UPDATE product SET sku = 'MP-005' WHERE slug = 'mini-pouch-mtr-station' AND sku IS DISTINCT FROM 'MP-005';
UPDATE product SET sku = 'MP-006' WHERE slug = 'mini-pouch-red-white-blue-bag-r' AND sku IS DISTINCT FROM 'MP-006';
UPDATE product SET sku = 'MP-007' WHERE slug = 'mini-pouch-red-white-blue-bag-b' AND sku IS DISTINCT FROM 'MP-007';
UPDATE product SET sku = 'MP-008' WHERE slug = 'mini-pouch-red-white-blue-bag-s' AND sku IS DISTINCT FROM 'MP-008';
UPDATE product SET sku = 'MP-009' WHERE slug = 'mini-pouch-cha-chaan-teng' AND sku IS DISTINCT FROM 'MP-009';
UPDATE product SET sku = 'MP-010' WHERE slug = 'mini-pouch-street-name-sign' AND sku IS DISTINCT FROM 'MP-010';
UPDATE product SET sku = 'MP-011' WHERE slug = 'mini-pouch-old-hong-kong' AND sku IS DISTINCT FROM 'MP-011';
UPDATE product SET sku = 'MP-012' WHERE slug = 'mini-pouch-canada' AND sku IS DISTINCT FROM 'MP-012';
