-- V11__reseed_products_from_csv.sql
-- Generated by generate_product_migration.py on 2026-06-20 02:26:10 UTC
-- Source: data/product-import/products_seed_v2.csv
--
-- Removes the previous product catalog and reseeds from CSV.
-- Upload images to object storage under products/<filename> before applying.

ALTER TABLE product ADD COLUMN IF NOT EXISTS sku VARCHAR(50);
CREATE UNIQUE INDEX IF NOT EXISTS ux_product_sku ON product (sku) WHERE sku IS NOT NULL;

-- Remove previous product data
UPDATE product SET image_media_id = NULL;
DELETE FROM category_product;
DELETE FROM product_translation;
DELETE FROM media WHERE entity_type = 'product';
DELETE FROM product;

-- Insert products
INSERT INTO product (name, slug, sku, description, price, active)
VALUES
  ('Makeup Bag Blue Bear', 'makeup-bag-blue-bear', 'MB-001', 'Adorable blue bear print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Ribbon Charm', 'makeup-bag-ribbon-charm', 'MB-002', 'Adorable pink ribbon print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, FALSE),
  ('Makeup Bag Pink Blossoms', 'makeup-bag-pink-blossoms', 'MB-003', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Cinnamoroll', 'makeup-bag-cinnamoroll', 'MB-004', 'Adorable cinnamoroll print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Vintage Garden', 'makeup-bag-vintage-garden', 'MB-005', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Fluffy Cat', 'makeup-bag-fluffy-cat', 'MB-006', 'Adorable cat print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Teddy Dot', 'makeup-bag-teddy-dot', 'MB-007', 'Adorable bear print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, FALSE),
  ('Makeup Bag Quilt Bloom', 'makeup-bag-quilt-bloom', 'MB-008', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Soft Cloud', 'makeup-bag-soft-cloud', 'MB-009', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, FALSE),
  ('Makeup Bag Golden Teddy', 'makeup-bag-golden-teddy', 'MB-010', 'Adorable bear print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Pink Bows', 'makeup-bag-pink-bows', 'MB-011', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Pastel Stripes', 'makeup-bag-pastel-stripes', 'MB-012', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Tissue Box Cover Blue Life Bread', 'tissue-box-cover-blue-life-bread', 'TC-001', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Green Life Bread', 'tissue-box-cover-green-life-bread', 'TC-002', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Demae Iccho', 'tissue-box-cover-demae-iccho', 'TC-003', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover White Rabbit Candy', 'tissue-box-cover-white-rabbit-candy', 'TC-004', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Aeroplane Chess', 'tissue-box-cover-aeroplane-chess', 'TC-005', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover MTR Station', 'tissue-box-cover-mtr-station', 'TC-006', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Red White Blue Bag R', 'tissue-box-cover-red-white-blue-bag-r', 'TC-007', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Red White Blue Bag B', 'tissue-box-cover-red-white-blue-bag-b', 'TC-008', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Red White Blue Bag S', 'tissue-box-cover-red-white-blue-bag-s', 'TC-009', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Cha Chaan Teng', 'tissue-box-cover-cha-chaan-teng', 'TC-010', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Street name sign', 'tissue-box-cover-street-name-sign', 'TC-011', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Old Hong Kong', 'tissue-box-cover-old-hong-kong', 'TC-012', 'Nostalgic Hong Kong print tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Tissue Box Cover Canada', 'tissue-box-cover-canada', 'TC-013', 'Celebrate Canada every day with this charming tissue box cover, perfect for your living room, office, or bedroom.', 30, TRUE),
  ('Mini Pouch Blue Life Bread', 'mini-pouch-blue-life-bread', 'MP-001', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Demae Iccho', 'mini-pouch-demae-iccho', 'MP-002', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch White Rabbit Candy', 'mini-pouch-white-rabbit-candy', 'MP-003', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Aeroplane Chess', 'mini-pouch-aeroplane-chess', 'MP-004', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch MTR Station', 'mini-pouch-mtr-station', 'MP-005', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Red White Blue Bag R', 'mini-pouch-red-white-blue-bag-r', 'MP-006', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Red White Blue Bag B', 'mini-pouch-red-white-blue-bag-b', 'MP-007', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Red White Blue Bag S', 'mini-pouch-red-white-blue-bag-s', 'MP-008', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Cha Chaan Teng', 'mini-pouch-cha-chaan-teng', 'MP-009', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Street name sign', 'mini-pouch-street-name-sign', 'MP-010', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Old Hong Kong', 'mini-pouch-old-hong-kong', 'MP-011', 'Nostalgic Hong Kong print mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Mini Pouch Canada', 'mini-pouch-canada', 'MP-012', 'Celebrate Canada every day with this charming mini pouch, perfect for storing coins, earbuds, lip balm, keys, cards, hair clips, medication, and other everyday essentials.', 24, TRUE),
  ('Makeup Bag Cherry Bliss', 'makeup-bag-cherry-bliss', 'MB-013', 'Adorable cherry print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Autumn Meadow', 'makeup-bag-autumn-meadow', 'MB-014', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE),
  ('Makeup Bag Cream Meadow', 'makeup-bag-cream-meadow', 'MB-015', 'Adorable floral print makeup bag, a compact cosmetic pouch ideal for travel and daily organization. Lightweight and durable with a secure zip closure.', 35, TRUE);

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/blue-bear-front.JPG', 'Makeup Bag Blue Bear', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-blue-bear'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/blue-bear-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/blue-bear-back.jpg', 'Makeup Bag Blue Bear', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-blue-bear'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/blue-bear-back.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/blue-bear-detail.jpg', 'Makeup Bag Blue Bear', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-blue-bear'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/blue-bear-detail.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/ribbon-charm-front.jpg', 'Makeup Bag Ribbon Charm', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-ribbon-charm'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/ribbon-charm-front.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pink-blossoms-front.JPG', 'Makeup Bag Pink Blossoms', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pink-blossoms'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pink-blossoms-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pink-blossoms-back.JPG', 'Makeup Bag Pink Blossoms', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pink-blossoms'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pink-blossoms-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pink-blossoms-detail.JPG', 'Makeup Bag Pink Blossoms', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pink-blossoms'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pink-blossoms-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cinnamoroll-front.JPG', 'Makeup Bag Cinnamoroll', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cinnamoroll'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cinnamoroll-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cinnamoroll-back.JPG', 'Makeup Bag Cinnamoroll', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cinnamoroll'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cinnamoroll-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cinnamoroll-detail.JPG', 'Makeup Bag Cinnamoroll', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cinnamoroll'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cinnamoroll-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/vintage-garden-front.JPG', 'Makeup Bag Vintage Garden', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-vintage-garden'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/vintage-garden-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/vintage-garden-back.JPG', 'Makeup Bag Vintage Garden', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-vintage-garden'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/vintage-garden-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/vintage-garden-detail.JPG', 'Makeup Bag Vintage Garden', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-vintage-garden'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/vintage-garden-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/fluffy-cat-front.JPG', 'Makeup Bag Fluffy Cat', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-fluffy-cat'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/fluffy-cat-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/fluffy-cat-back.JPG', 'Makeup Bag Fluffy Cat', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-fluffy-cat'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/fluffy-cat-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/fluffy-cat-detail.JPG', 'Makeup Bag Fluffy Cat', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-fluffy-cat'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/fluffy-cat-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/teddy-dot-front.jpg', 'Makeup Bag Teddy Dot', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-teddy-dot'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/teddy-dot-front.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/quilt-bloom-front.JPG', 'Makeup Bag Quilt Bloom', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-quilt-bloom'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/quilt-bloom-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/quilt-bloom-back.JPG', 'Makeup Bag Quilt Bloom', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-quilt-bloom'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/quilt-bloom-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/quilt-bloom-detail.JPG', 'Makeup Bag Quilt Bloom', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-quilt-bloom'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/quilt-bloom-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/soft-cloud-front.jpg', 'Makeup Bag Soft Cloud', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-soft-cloud'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/soft-cloud-front.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/golden-teddy-front.JPG', 'Makeup Bag Golden Teddy', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-golden-teddy'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/golden-teddy-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/golden-teddy-back.JPG', 'Makeup Bag Golden Teddy', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-golden-teddy'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/golden-teddy-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/golden-teddy-detail.JPG', 'Makeup Bag Golden Teddy', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-golden-teddy'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/golden-teddy-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pink-bows-front.JPG', 'Makeup Bag Pink Bows', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pink-bows'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pink-bows-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pink-bows-back.JPG', 'Makeup Bag Pink Bows', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pink-bows'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pink-bows-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pink-bows-detail.JPG', 'Makeup Bag Pink Bows', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pink-bows'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pink-bows-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pastel-stripes-front.JPG', 'Makeup Bag Pastel Stripes', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pastel-stripes'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pastel-stripes-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pastel-stripes-back.JPG', 'Makeup Bag Pastel Stripes', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pastel-stripes'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pastel-stripes-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/pastel-stripes-detail.JPG', 'Makeup Bag Pastel Stripes', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-pastel-stripes'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/pastel-stripes-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-blue-life-bread.JPG', 'Tissue Box Cover Blue Life Bread', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-blue-life-bread'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-blue-life-bread.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-green-life-bread.JPG', 'Tissue Box Cover Green Life Bread', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-green-life-bread'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-green-life-bread.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-demae-iccho.JPG', 'Tissue Box Cover Demae Iccho', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-demae-iccho'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-demae-iccho.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-white-rabbit-candy.JPG', 'Tissue Box Cover White Rabbit Candy', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-white-rabbit-candy'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-white-rabbit-candy.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-aeroplane-chess.JPG', 'Tissue Box Cover Aeroplane Chess', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-aeroplane-chess'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-aeroplane-chess.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-mtr-station.JPG', 'Tissue Box Cover MTR Station', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-mtr-station'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-mtr-station.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-red-white-blue-bag-r.JPG', 'Tissue Box Cover Red White Blue Bag R', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-red-white-blue-bag-r'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-red-white-blue-bag-r.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-red-white-blue-bag-b.JPG', 'Tissue Box Cover Red White Blue Bag B', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-red-white-blue-bag-b'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-red-white-blue-bag-b.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-red-white-blue-bag-s.JPG', 'Tissue Box Cover Red White Blue Bag S', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-red-white-blue-bag-s'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-red-white-blue-bag-s.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-cha-chaan-teng.JPG', 'Tissue Box Cover Cha Chaan Teng', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-cha-chaan-teng'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-cha-chaan-teng.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-street-name-sign.jpg', 'Tissue Box Cover Street name sign', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-street-name-sign'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-street-name-sign.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-old-hong-kong.JPG', 'Tissue Box Cover Old Hong Kong', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-old-hong-kong'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-old-hong-kong.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/tissue-box-cover-canada.JPG', 'Tissue Box Cover Canada', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'tissue-box-cover-canada'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/tissue-box-cover-canada.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-blue-life-bread.JPG', 'Mini Pouch Blue Life Bread', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-blue-life-bread'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-blue-life-bread.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-blue-life-bread-detail.JPG', 'Mini Pouch Blue Life Bread', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-blue-life-bread'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-blue-life-bread-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-demae-iccho.JPG', 'Mini Pouch Demae Iccho', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-demae-iccho'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-demae-iccho.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-white-rabbit-candy.JPG', 'Mini Pouch White Rabbit Candy', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-white-rabbit-candy'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-white-rabbit-candy.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-aeroplane-chess-front.JPG', 'Mini Pouch Aeroplane Chess', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-aeroplane-chess'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-aeroplane-chess-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-aeroplane-chess-back.JPG', 'Mini Pouch Aeroplane Chess', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-aeroplane-chess'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-aeroplane-chess-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-mtr-station.JPG', 'Mini Pouch MTR Station', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-mtr-station'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-mtr-station.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-mtr-station-detail.JPG', 'Mini Pouch MTR Station', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-mtr-station'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-mtr-station-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-red-white-blue-bag-r.JPG', 'Mini Pouch Red White Blue Bag R', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-red-white-blue-bag-r'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-red-white-blue-bag-r.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-red-white-blue-bag-b.JPG', 'Mini Pouch Red White Blue Bag B', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-red-white-blue-bag-b'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-red-white-blue-bag-b.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-red-white-blue-bag-s.JPG', 'Mini Pouch Red White Blue Bag S', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-red-white-blue-bag-s'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-red-white-blue-bag-s.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-cha-chaan-teng-front.JPG', 'Mini Pouch Cha Chaan Teng', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-cha-chaan-teng'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-cha-chaan-teng-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-cha-chaan-teng-back.JPG', 'Mini Pouch Cha Chaan Teng', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-cha-chaan-teng'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-cha-chaan-teng-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-street-name-sign-front.JPG', 'Mini Pouch Street name sign', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-street-name-sign'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-street-name-sign-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-street-name-sign-back.JPG', 'Mini Pouch Street name sign', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-street-name-sign'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-street-name-sign-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-old-hong-kong-front.jpg', 'Mini Pouch Old Hong Kong', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-old-hong-kong'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-old-hong-kong-front.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-old-hong-kong-back.JPG', 'Mini Pouch Old Hong Kong', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-old-hong-kong'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-old-hong-kong-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-canada.JPG', 'Mini Pouch Canada', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-canada'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-canada.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/mini-pouch-canada-detail.jpg', 'Mini Pouch Canada', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'mini-pouch-canada'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/mini-pouch-canada-detail.jpg'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cherry-bliss-front.JPG', 'Makeup Bag Cherry Bliss', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cherry-bliss'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cherry-bliss-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cherry-bliss-back.JPG', 'Makeup Bag Cherry Bliss', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cherry-bliss'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cherry-bliss-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cherry-bliss-detail.JPG', 'Makeup Bag Cherry Bliss', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cherry-bliss'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cherry-bliss-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/autumn-meadow-front.JPG', 'Makeup Bag Autumn Meadow', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-autumn-meadow'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/autumn-meadow-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/autumn-meadow-back.JPG', 'Makeup Bag Autumn Meadow', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-autumn-meadow'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/autumn-meadow-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/autumn-meadow-detail.JPG', 'Makeup Bag Autumn Meadow', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-autumn-meadow'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/autumn-meadow-detail.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cream-meadow-front.JPG', 'Makeup Bag Cream Meadow', TRUE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cream-meadow'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cream-meadow-front.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cream-meadow-back.JPG', 'Makeup Bag Cream Meadow', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cream-meadow'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cream-meadow-back.JPG'
  );

INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)
SELECT 'products/cream-meadow-detail.JPG', 'Makeup Bag Cream Meadow', FALSE, now(), 'product', p.id
FROM product p
WHERE p.slug = 'makeup-bag-cream-meadow'
  AND NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = 'products/cream-meadow-detail.JPG'
  );

-- Link primary media to product.image_media_id
UPDATE product
SET image_media_id = m.id
FROM media m
WHERE m.entity_type = 'product'
  AND m.entity_id = product.id
  AND m.is_primary = TRUE;

-- Link products to categories
INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-blue-bear'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-ribbon-charm'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-pink-blossoms'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-cinnamoroll'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-vintage-garden'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-fluffy-cat'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-teddy-dot'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-quilt-bloom'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-soft-cloud'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-golden-teddy'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-pink-bows'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-pastel-stripes'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-blue-life-bread'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-green-life-bread'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-demae-iccho'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-white-rabbit-candy'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-aeroplane-chess'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-mtr-station'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-red-white-blue-bag-r'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-red-white-blue-bag-b'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-red-white-blue-bag-s'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-cha-chaan-teng'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-street-name-sign'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-old-hong-kong'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'tissue-box-cover-canada'
WHERE c.slug = 'hk-tissue-box-covers'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-blue-life-bread'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-demae-iccho'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-white-rabbit-candy'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-aeroplane-chess'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-mtr-station'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-red-white-blue-bag-r'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-red-white-blue-bag-b'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-red-white-blue-bag-s'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-cha-chaan-teng'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-street-name-sign'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-old-hong-kong'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'mini-pouch-canada'
WHERE c.slug = 'hk-coin-pouches'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-cherry-bliss'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-autumn-meadow'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

INSERT INTO category_product (category_id, product_id)
SELECT c.id, p.id
FROM category c
JOIN product p ON p.slug = 'makeup-bag-cream-meadow'
WHERE c.slug = 'makeup-bags'
  AND NOT EXISTS (
    SELECT 1 FROM category_product cp
    WHERE cp.category_id = c.id AND cp.product_id = p.id
  );

-- Seed Traditional Chinese translations
INSERT INTO product_translation (product_id, locale, name, description)
VALUES
  ((SELECT id FROM product WHERE slug='makeup-bag-blue-bear'), 'zh-HK', '藍色小熊化妝包', '可愛藍色小熊圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-ribbon-charm'), 'zh-HK', '粉紅色蝴蝶結化妝包', '可愛粉紅色蝴蝶結圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-pink-blossoms'), 'zh-HK', '粉紅色碎花化妝包', '可愛粉紅色碎花圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-cinnamoroll'), 'zh-HK', '肉桂狗化妝包', '可愛肉桂狗圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-vintage-garden'), 'zh-HK', '白色碎花化妝包', '可愛白色碎花圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-fluffy-cat'), 'zh-HK', '藍色小貓化妝包', '可愛藍色小貓圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-teddy-dot'), 'zh-HK', '波點小熊化妝包', '可愛波點小熊圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-quilt-bloom'), 'zh-HK', '灰色碎花化妝包', '可愛灰色碎花圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-soft-cloud'), 'zh-HK', '藍色暗花化妝包', '低調藍色暗花圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-golden-teddy'), 'zh-HK', '燈芯絨小熊化妝包', '可愛燈芯絨小熊圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-pink-bows'), 'zh-HK', '蝴蝶結碎花化妝包', '可愛蝴蝶結碎花化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-pastel-stripes'), 'zh-HK', '淡粉色暗花化妝包', '低調粉色暗花圖圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-blue-life-bread'), 'zh-HK', '藍色生命麵包紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-green-life-bread'), 'zh-HK', '綠色生命麵包紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-demae-iccho'), 'zh-HK', '出前一丁紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-white-rabbit-candy'), 'zh-HK', '白兔糖紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-aeroplane-chess'), 'zh-HK', '飛行棋紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-mtr-station'), 'zh-HK', '香港地鐵主題紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-red-white-blue-bag-r'), 'zh-HK', '紅色紅白藍紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-red-white-blue-bag-b'), 'zh-HK', '藍色紅白藍紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-red-white-blue-bag-s'), 'zh-HK', '直間紅白藍紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-cha-chaan-teng'), 'zh-HK', '茶餐廳主題紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-street-name-sign'), 'zh-HK', '香港招牌主題紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-old-hong-kong'), 'zh-HK', '舊香港主題紙巾套', '懷舊香港印花紙巾盒套，為客廳、辦公室或睡房增添一份香港情懷。'),
  ((SELECT id FROM product WHERE slug='tissue-box-cover-canada'), 'zh-HK', '加拿大主題紙巾套', '充滿加拿大特色的紙巾盒套，為客廳、辦公室或睡房增添一份溫暖的加拿大風情。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-blue-life-bread'), 'zh-HK', '藍色生命麵包散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-demae-iccho'), 'zh-HK', '出前一丁散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-white-rabbit-candy'), 'zh-HK', '白兔糖散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-aeroplane-chess'), 'zh-HK', '飛行棋散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-mtr-station'), 'zh-HK', '香港地鐵主題散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-red-white-blue-bag-r'), 'zh-HK', '紅色紅白藍散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-red-white-blue-bag-b'), 'zh-HK', '藍色紅白藍散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-red-white-blue-bag-s'), 'zh-HK', '直間紅白藍散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-cha-chaan-teng'), 'zh-HK', '茶餐廳主題散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-street-name-sign'), 'zh-HK', '香港招牌主題散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-old-hong-kong'), 'zh-HK', '舊香港主題散子包', '懷舊香港印花迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='mini-pouch-canada'), 'zh-HK', '加拿大主題散子包', '充滿加拿大特色的迷你收納袋，適合存放零錢、耳機、潤唇膏、鑰匙、卡片、髮夾、藥物及其他日常小物。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-cherry-bliss'), 'zh-HK', '紅白色車厘子化妝包', '可愛車厘子圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-autumn-meadow'), 'zh-HK', '燈芯絨啡色碎花化妝包', '可愛燈芯絨碎花圖案化妝包，適合旅行與日常整理。'),
  ((SELECT id FROM product WHERE slug='makeup-bag-cream-meadow'), 'zh-HK', '燈芯絨白色碎花化妝包', '可愛燈芯絨碎花圖案化妝包，適合旅行與日常整理。')
ON CONFLICT (product_id, locale) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    updated_at = now();
