# Build stage
FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN chmod +x mvnw
RUN ./mvnw --batch-mode -DskipTests dependency:go-offline

COPY src ./src
RUN ./mvnw --batch-mode -DskipTests package -DskipTests -Dmaven.javadoc.skip=true

# Runtime stage
FROM eclipse-temurin:21-jre
WORKDIR /app

ENV SPRING_PROFILES_ACTIVE=staging
EXPOSE 8080

COPY --from=builder /app/target/online-store-api-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
