#!/usr/bin/env python3
"""
Generate a Flyway migration from data/product-import/products_seed.csv.

Usage:
  python data/product-import/generate_product_migration.py
  python data/product-import/generate_product_migration.py --check-only

Outputs:
  backend/online-store-api/src/main/resources/db/migration/V9__reseed_products_from_csv.sql

Before running the migration, upload images to object storage (MinIO/R2) under
  products/<filename>
using the keys referenced in the generated media rows.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = ROOT / "data" / "product-import" / "products_seed_v2.csv"
IMAGE_DIR = ROOT / "resources" / "images" / "products"
MIGRATION_DIR = ROOT / "backend" / "online-store-api" / "src" / "main" / "resources" / "db" / "migration"
MIGRATION_FILE = MIGRATION_DIR / "V11__reseed_products_from_csv.sql"
SKU_MIGRATION_FILE = MIGRATION_DIR / "V12__add_product_sku.sql"

CATEGORY_ALIASES = {
    "tissue-box-cover": "hk-tissue-box-covers",
    "mini-pouch": "hk-coin-pouches",
}

STORAGE_PREFIX = "products"


def slugify(name: str) -> str:
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug or "product"


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def parse_bool(value: str) -> bool:
    return value.strip().lower() in {"yes", "true", "1", "y"}


def parse_image_list(value: str) -> list[str]:
    if not value or not value.strip():
        return []
    return [part.strip() for part in value.split(",") if part.strip()]


def resolve_image_filename(filename: str, image_index: dict[str, str]) -> str | None:
    key = filename.lower()
    return image_index.get(key)


def load_image_index() -> dict[str, str]:
    if not IMAGE_DIR.is_dir():
        return {}
    return {path.name.lower(): path.name for path in IMAGE_DIR.iterdir() if path.is_file()}


def load_products() -> list[dict]:
    with CSV_PATH.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def validate_products(products: list[dict], image_index: dict[str, str]) -> list[str]:
    errors: list[str] = []
    warnings: list[str] = []
    seen_skus: set[str] = set()
    seen_slugs: dict[str, str] = {}

    for row in products:
        sku = row["sku"].strip()
        if sku in seen_skus:
            errors.append(f"Duplicate sku: {sku}")
        seen_skus.add(sku)

        slug = slugify(row["name_en"])
        if slug in seen_slugs and seen_slugs[slug] != sku:
            errors.append(f"Duplicate slug '{slug}' for {sku} and {seen_slugs[slug]}")
        seen_slugs[slug] = sku

        images = parse_image_list(row.get("image_files", ""))
        primary = row.get("primary_image", "").strip()
        if images and primary and primary.lower() not in {img.lower() for img in images}:
            errors.append(f"{sku}: primary_image '{primary}' not in image_files")

        for image in images:
            if resolve_image_filename(image, image_index) is None:
                errors.append(f"{sku}: missing image file '{image}' in {IMAGE_DIR}")

        if not images:
            warnings.append(f"{sku}: no images listed (product will be inserted without media)")

        categories = [c.strip() for c in row.get("categories", "").split(",") if c.strip()]
        for category in categories:
            normalized = CATEGORY_ALIASES.get(category, category)
            if normalized != category:
                warnings.append(f"{sku}: category alias '{category}' -> '{normalized}'")

    return errors, warnings


def build_unique_slugs(products: list[dict]) -> dict[str, str]:
    slug_by_sku: dict[str, str] = {}
    used: set[str] = set()

    for row in products:
        sku = row["sku"].strip()
        base = slugify(row["name_en"])
        slug = base
        if slug in used:
            slug = f"{base}-{sku.lower()}"
        used.add(slug)
        slug_by_sku[sku] = slug

    return slug_by_sku


def generate_migration(products: list[dict], image_index: dict[str, str]) -> str:
    slug_by_sku = build_unique_slugs(products)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = [
        "-- V11__reseed_products_from_csv.sql",
        f"-- Generated by generate_product_migration.py on {generated_at}",
        "-- Source: data/product-import/products_seed_v2.csv",
        "--",
        "-- Removes the previous product catalog and reseeds from CSV.",
        "-- Upload images to object storage under products/<filename> before applying.",
        "",
        "ALTER TABLE product ADD COLUMN IF NOT EXISTS sku VARCHAR(50);",
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_product_sku ON product (sku) WHERE sku IS NOT NULL;",
        "",
        "-- Remove previous product data",
        "UPDATE product SET image_media_id = NULL;",
        "DELETE FROM category_product;",
        "DELETE FROM product_translation;",
        "DELETE FROM media WHERE entity_type = 'product';",
        "DELETE FROM product;",
        "",
        "-- Insert products",
        "INSERT INTO product (name, slug, sku, description, price, active)",
        "VALUES",
    ]

    product_values: list[str] = []
    for row in products:
        sku = row["sku"].strip()
        slug = slug_by_sku[sku]
        active = "TRUE" if parse_bool(row.get("active", "yes")) else "FALSE"
        product_values.append(
            f"  ({sql_str(row['name_en'].strip())}, {sql_str(slug)}, {sql_str(sku)}, {sql_str(row.get('description_en', '').strip())}, {row['price'].strip()}, {active})"
        )
    lines.append(",\n".join(product_values) + ";")
    lines.append("")

    for row in products:
        sku = row["sku"].strip()
        slug = slug_by_sku[sku]
        name = row["name_en"].strip()
        images = parse_image_list(row.get("image_files", ""))
        primary = row.get("primary_image", "").strip().lower()
        if not primary and images:
            primary = images[0].lower()

        for image in images:
            resolved = resolve_image_filename(image, image_index)
            if resolved is None:
                continue
            storage_key = f"{STORAGE_PREFIX}/{resolved}"
            is_primary = "TRUE" if image.lower() == primary else "FALSE"
            lines.extend(
                [
                    "INSERT INTO media (storage_key, alt, is_primary, created_at, entity_type, entity_id)",
                    f"SELECT {sql_str(storage_key)}, {sql_str(name)}, {is_primary}, now(), 'product', p.id",
                    "FROM product p",
                    f"WHERE p.slug = {sql_str(slug)}",
                    "  AND NOT EXISTS (",
                    "    SELECT 1 FROM media m",
                    f"    WHERE m.entity_type = 'product' AND m.entity_id = p.id AND m.storage_key = {sql_str(storage_key)}",
                    "  );",
                    "",
                ]
            )

    lines.extend(
        [
            "-- Link primary media to product.image_media_id",
            "UPDATE product",
            "SET image_media_id = m.id",
            "FROM media m",
            "WHERE m.entity_type = 'product'",
            "  AND m.entity_id = product.id",
            "  AND m.is_primary = TRUE;",
            "",
            "-- Link products to categories",
        ]
    )

    for row in products:
        sku = row["sku"].strip()
        slug = slug_by_sku[sku]
        categories = [c.strip() for c in row.get("categories", "").split(",") if c.strip()]
        for category in categories:
            category_slug = CATEGORY_ALIASES.get(category, category)
            lines.extend(
                [
                    "INSERT INTO category_product (category_id, product_id)",
                    f"SELECT c.id, p.id",
                    "FROM category c",
                    "JOIN product p ON p.slug = " + sql_str(slug),
                    f"WHERE c.slug = {sql_str(category_slug)}",
                    "  AND NOT EXISTS (",
                    "    SELECT 1 FROM category_product cp",
                    "    WHERE cp.category_id = c.id AND cp.product_id = p.id",
                    "  );",
                    "",
                ]
            )

    translation_rows: list[str] = []
    for row in products:
        name_zh = row.get("name_zh", "").strip()
        if not name_zh:
            continue
        sku = row["sku"].strip()
        slug = slug_by_sku[sku]
        desc_zh = row.get("description_zh", "").strip()
        translation_rows.append(
            f"  ((SELECT id FROM product WHERE slug={sql_str(slug)}), 'zh-HK', {sql_str(name_zh)}, {sql_str(desc_zh)})"
        )

    if translation_rows:
        lines.extend(
            [
                "-- Seed Traditional Chinese translations",
                "INSERT INTO product_translation (product_id, locale, name, description)",
                "VALUES",
                ",\n".join(translation_rows),
                "ON CONFLICT (product_id, locale) DO UPDATE",
                "SET name = EXCLUDED.name,",
                "    description = EXCLUDED.description,",
                "    updated_at = now();",
            ]
        )

    return "\n".join(lines) + "\n"


def generate_sku_backfill_migration(products: list[dict]) -> str:
    slug_by_sku = build_unique_slugs(products)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = [
        "-- V12__add_product_sku.sql",
        f"-- Generated by generate_product_migration.py on {generated_at}",
        "-- Adds sku column and backfills values for databases that already ran V9 without sku.",
        "",
        "ALTER TABLE product ADD COLUMN IF NOT EXISTS sku VARCHAR(50);",
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_product_sku ON product (sku) WHERE sku IS NOT NULL;",
        "",
    ]

    for row in products:
        sku = row["sku"].strip()
        slug = slug_by_sku[sku]
        lines.append(f"UPDATE product SET sku = {sql_str(sku)} WHERE slug = {sql_str(slug)} AND sku IS DISTINCT FROM {sql_str(sku)};")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate product seed Flyway migration from CSV")
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Validate CSV and image files without writing migration SQL",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=MIGRATION_FILE,
        help=f"Output SQL file (default: {MIGRATION_FILE.relative_to(ROOT)})",
    )
    args = parser.parse_args()

    if not CSV_PATH.is_file():
        print(f"ERROR: CSV not found: {CSV_PATH}", file=sys.stderr)
        return 1

    products = load_products()
    image_index = load_image_index()
    errors, warnings = validate_products(products, image_index)

    for warning in warnings:
        print(f"WARNING: {warning}")

    if errors:
        print("Validation failed:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    print(f"Validated {len(products)} products, {len(image_index)} image files on disk.")

    if args.check_only:
        return 0

    sql = generate_migration(products, image_index)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    print(f"Wrote migration: {args.output.relative_to(ROOT)}")

    sku_sql = generate_sku_backfill_migration(products)
    SKU_MIGRATION_FILE.parent.mkdir(parents=True, exist_ok=True)
    SKU_MIGRATION_FILE.write_text(sku_sql, encoding="utf-8")
    print(f"Wrote migration: {SKU_MIGRATION_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
